{% set name = "astor" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/astor-{{ version }}.tar.gz
  sha256: 37a6eed8b371f1228db08234ed7f6cfdc7817a3ed3824797e20cbb11dc2a7862

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python =2.7|>=3.4
    - pip
  run:
    - python =2.7|>=3.4

test:
  imports:
    - astor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/berkerpeksag/astor
  license: BSD-3-Clause
  summary: 'Read, rewrite, and write Python ASTs nicely'
  license_file: LICENSE
  description: |
    astor is designed to allow easy manipulation of Python source via the AST.
  doc_url: http://astor.readthedocs.io/en/latest/
  dev_url: https://github.com/berkerpeksag/astor

extra:
  recipe-maintainers:
    - drewokane
    - xhochy
