{% set name = "astor" %}
{% set version = "0.8.0" %}
{% set sha256 = "37a6eed8b371f1228db08234ed7f6cfdc7817a3ed3824797e20cbb11dc2a7862" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - astor

about:
  home: https://github.com/berkerpeksag/astor
  license: BSD-3-Clause
  summary: 'Read, rewrite, and write Python ASTs nicely'
  license_file: LICENSE
  description: |
    astor is designed to allow easy manipulation of Python source via the AST.
  doc_url: http://astor.readthedocs.io/en/latest/
  dev_url: https://github.com/berkerpeksag/astor

extra:
  recipe-maintainers:
    - drewokane
