{% set name = "astor" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a6effda93f4e1ce9f618779b2dd1d9d84f1e32812c23a29b3fff6fd7f63fa5e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - astor

about:
  home: https://github.com/berkerpeksag/astor
  license: BSD-3-Clause
  summary: 'Read, rewrite, and write Python ASTs nicely'
  license_file: LICENSE
  description: |
    astor is designed to allow easy manipulation of Python source via the AST.
  doc_url: http://astor.readthedocs.io/en/latest/
  dev_url: https://github.com/berkerpeksag/astor

extra:
  recipe-maintainers:
    - drewokane
    - xhochy
